language: java

install: true

before_deploy:
- echo $projectversion
- mvn package
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- export GIT_TAG=$projectversion-B$TRAVIS_BUILD_NUMBER
- git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER\s\s\s\sHKOWeather-API-x.x.x.jar - Simple clean file, but no dependencies.\s\sHKOWeather-API-x.x.x-jar-with-dependencies.jar - with dependencies. (Recommended)\s\sHKOWeather-API-x.x.x-javadoc.jar - JavaDoc File"
- git push -q https://$GITPERM@github.com/mob41/HKOWeather-API --tags
- ls -R

deploy:
  skip_cleanup: true
  provider: releases
  api_key: $GITPERM
  file: 
    - target/HKOWeather-API-$projectversion.jar
    - target/HKOWeather-API-$projectversion-jar-with-dependencies.jar
    - target/HKOWeather-API-$projectversion-javadoc.jar
  on:
    tags: false
    all_branches: true
    
branches:
  only:
    - master

env:
- projectversion=0.0.1-SNAPSHOT